"""Deterministic manifest and verification for repository state authority."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

SCHEMA_VERSION = "1.0"
MANIFEST_PATH = Path("generated/state-authority-manifest.json")

# Every Class 2 projection must be fully regenerated by repository code.
GENERATED_PROJECTIONS: tuple[dict[str, Any], ...] = (
    {"path": "generated/publication-index.md", "generator": "nks generate-views", "sources": ["records/publications/*.json"]},
    {"path": "generated/proof-index.md", "generator": "nks generate-views", "sources": ["records/proofs/*.json"]},
    {"path": "generated/visual-package-index.md", "generator": "nks generate-views", "sources": ["records/visuals/*.json"]},
    {"path": "generated/visual-request-index.md", "generator": "nks generate-views", "sources": ["records/visual-requests/*.json"]},
    {"path": "generated/feedback-index.md", "generator": "nks generate-views", "sources": ["records/feedback/*.json"]},
    {"path": "generated/event-index.md", "generator": "nks generate-views", "sources": ["records/events/*.json"]},
    {"path": "generated/graph-index.md", "generator": "nks generate-views", "sources": ["records/**/*.json"]},
    {"path": "generated/audit-report.md", "generator": "nks generate-views", "sources": ["records/**/*.json"]},
    {"path": "generated/runtime-status-report.md", "generator": "nks generate-views", "sources": ["records/**/*.json"]},
    {"path": "generated/corpus-health-dashboard.md", "generator": "nks generate-views", "sources": ["records/**/*.json"]},
    {"path": "generated/publication-package-index.md", "generator": "nks generate-views", "sources": ["*/*/receipt.json"]},
    {"path": "generated/ecosystem-capabilities.md", "generator": "nks generate-views", "sources": ["records/capabilities/ecosystem-capabilities.json"]},
    {"path": "generated/audit/repository-audit.md", "generator": "nks audit-repository", "sources": ["repository tree", "records/**/*.json"]},
    {"path": "generated/audit/repository-audit.json", "generator": "nks audit-repository", "sources": ["repository tree", "records/**/*.json"]},
)


def build_authority_manifest() -> dict[str, Any]:
    """Return the deterministic repository authority manifest."""
    return {
        "schema_version": SCHEMA_VERSION,
        "authority_precedence": [
            "canonical_machine_state",
            "generated_authoritative_projection",
            "narrative_or_historical_material",
        ],
        "canonical_machine_state": {
            "class": 1,
            "paths": ["records/**/*.json"],
            "manually_editable": True,
            "note": "Changes require schema validation and governed state transitions.",
        },
        "generated_authoritative_projections": [
            {"class": 2, "manually_editable": False, **projection}
            for projection in GENERATED_PROJECTIONS
        ],
        "narrative_or_historical_material": {
            "class": 3,
            "paths": ["docs/**/*.md", "runtime/STATUS.md", "README.md"],
            "authoritative_for_current_state": False,
            "exceptions": ["docs/state-authority-model.md"],
        },
    }


def render_authority_manifest() -> str:
    """Render stable JSON suitable for version control."""
    return json.dumps(build_authority_manifest(), indent=2, sort_keys=True) + "\n"


def write_authority_manifest(repository_root: Path) -> Path:
    """Write the generated manifest and return its path."""
    output = repository_root / MANIFEST_PATH
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_authority_manifest(), encoding="utf-8")
    return output


def verify_authority_manifest(repository_root: Path) -> list[str]:
    """Return authority violations without mutating the repository."""
    violations: list[str] = []
    manifest_path = repository_root / MANIFEST_PATH
    if not manifest_path.exists():
        violations.append(f"missing generated authority manifest: {MANIFEST_PATH}")
    else:
        try:
            observed = json.loads(manifest_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            violations.append(f"invalid generated authority manifest: {MANIFEST_PATH}")
        else:
            if observed != build_authority_manifest():
                violations.append(f"stale generated authority manifest: {MANIFEST_PATH}")

    for projection in GENERATED_PROJECTIONS:
        path = repository_root / projection["path"]
        if not path.exists():
            violations.append(f"missing Class 2 projection: {projection['path']}")

    return violations


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("write", "verify"))
    parser.add_argument("repository_root", nargs="?", default=".")
    args = parser.parse_args()
    root = Path(args.repository_root).resolve()

    if args.command == "write":
        print(write_authority_manifest(root))
        return 0

    violations = verify_authority_manifest(root)
    if violations:
        for violation in violations:
            print(violation)
        return 1
    print("state authority manifest: verified")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
